# Generated by Django 4.1.3 on 2022-11-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogproject_descriptoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('descriptoin', models.TextField()),
                ('data', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='BlogProject',
        ),
    ]
