# Generated by Django 4.1.3 on 2022-12-20 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_delete_blogproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/media/images/'),
            preserve_default=False,
        ),
    ]
