# Generated by Django 4.1.3 on 2022-12-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blog_data_remove_blog_image_blog_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
